version: 2.1
jobs:
  build:
    machine: true
    resource_class: 2xlarge
    steps:
     - checkout
     - run:
          name: "Build dockerized environment locally"
          command: ./pb-dev --build-env
     - run:
          name: "Run tests"
          command: ./pb-dev --test-in-container


