# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'                                                                                                                                                                                                          
source 'git@github.com:StandardCyborg/SCCocoaPods.git'

target 'ProtobagOSX' do
  pod 'ProtobagCocoa', :podspec => '../../ProtobagCocoa.podspec.json'
  pod 'ProtobagCocoaTest', :podspec => 'ProtobagCocoaTest.podspec.json'
  pod 'GTestCpp', :podspec => 'GTestCpp.podspec.json'
  # pod 'PyBind11C++', :podspec => 'PyBind11C++.podspec'
  # pod 'ProtobagPyNative', :podspec => 'ProtobagPyNative.podspec'
end

target 'protobag_native' do
  pod 'ProtobagCocoa', :podspec => '../../ProtobagCocoa.podspec.json'
  pod 'ProtobagCocoaTest', :podspec => 'ProtobagCocoaTest.podspec.json'
  pod 'GTestCpp', :podspec => 'GTestCpp.podspec.json'
  # pod 'PyBind11C++', :podspec => 'PyBind11C++.podspec'
  pod 'ProtobagPyNative', :podspec => 'ProtobagPyNative.podspec'
end
