# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: moof.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='moof.proto',
  package='my_package',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nmoof.proto\x12\nmy_package\"\x11\n\x04Moof\x12\t\n\x01x\x18\x01 \x01(\tb\x06proto3'
)




_MOOF = _descriptor.Descriptor(
  name='Moof',
  full_name='my_package.Moof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='my_package.Moof.x', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=43,
)

DESCRIPTOR.message_types_by_name['Moof'] = _MOOF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Moof = _reflection.GeneratedProtocolMessageType('Moof', (_message.Message,), {
  'DESCRIPTOR' : _MOOF,
  '__module__' : 'moof_pb2'
  # @@protoc_insertion_point(class_scope:my_package.Moof)
  })
_sym_db.RegisterMessage(Moof)


# @@protoc_insertion_point(module_scope)
